CREATE TABLE CONTA (
   ID INT AUTO_INCREMENT PRIMARY KEY, 
   NOME_CLIENTE VARCHAR, 
   SALDO FLOAT
);

INSERT INTO CONTA (ID, NOME_CLIENTE, SALDO)
VALUES ('João Silva', 1000.50);

INSERT INTO CONTA (ID, NOME_CLIENTE, SALDO)
VALUES ('Maria Oliveira', 1500.75);

INSERT INTO CONTA (ID, NOME_CLIENTE, SALDO)
VALUES ('Carlos Pereira', 800.20);

INSERT INTO CONTA (ID, NOME_CLIENTE, SALDO)
VALUES ('Ana Souza', 2000.00);

INSERT INTO CONTA (ID, NOME_CLIENTE, SALDO)
VALUES ('Luana Santos', 300.90);
