CREATE TABLE CONTA (
   ID INT AUTO_INCREMENT PRIMARY KEY, 
   NOME_CLIENTE VARCHAR, 
   SALDO FLOAT
);

INSERT INTO CONTA (ID, NOME_CLIENTE, SALDO)
VALUES (1,'João Silva', 1000.50);

INSERT INTO CONTA (ID, NOME_CLIENTE, SALDO)
VALUES (2, 'Maria Oliveira', 1500.75);

INSERT INTO CONTA (ID, NOME_CLIENTE, SALDO)
VALUES (3, 'Carlos Pereira', 800.20);

INSERT INTO CONTA (ID, NOME_CLIENTE, SALDO)
VALUES (4, 'Ana Souza', 2000.00);

INSERT INTO CONTA (ID, NOME_CLIENTE, SALDO)
VALUES (5, 'Luana Santos', 300.90);